// <auto-generated />
using System;
using CLIMFinders.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLIMFinders.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250208065543_change vechile tbl struct")]
    partial class changevechiletblstruct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Businesses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Searches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Subscriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("TierId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.VehicleColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Turquoise"
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acura"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Buick"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cadillac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chrysler"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Genesis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "GMC"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Infiniti"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lotus"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 31,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Saab"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ColorId");

                    b.HasIndex("MakeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Given.DataContext.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleNanme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleNanme = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            RoleNanme = "Users"
                        },
                        new
                        {
                            Id = 3,
                            RoleNanme = "Tow"
                        },
                        new
                        {
                            Id = 4,
                            RoleNanme = "Impound"
                        });
                });

            modelBuilder.Entity("Given.DataContext.Entities.SubscriptionPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(2858),
                            Amount = 0m,
                            Duration = 0,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(2874),
                            Tier = "Free Tier"
                        },
                        new
                        {
                            Id = 2,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(2877),
                            Amount = 10m,
                            Duration = 1,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(2877),
                            Tier = "Paid Tier"
                        });
                });

            modelBuilder.Entity("Given.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(3972),
                            ConfirmedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(3977),
                            Email = "admin@admin.com",
                            FullName = "SuperAdmin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 8, 12, 25, 42, 911, DateTimeKind.Local).AddTicks(3974),
                            Password = "MDAwMA==",
                            PasswordHash = new byte[] { 78, 175, 165, 82, 128, 227, 210, 20, 132, 137, 62, 128, 4, 180, 42, 104, 104, 80, 71, 12, 53, 253, 204, 145, 16, 162, 153, 66, 190, 75, 128, 184, 200, 135, 186, 248, 224, 13, 98, 103, 32, 158, 178, 251, 26, 183, 59, 237, 138, 215, 96, 67, 244, 103, 55, 186, 230, 153, 17, 7, 4, 115, 125, 0, 195, 212, 36, 240, 225, 132, 111, 228, 152, 235, 57, 236, 253, 17, 245, 143, 219, 185, 61, 17, 141, 231, 66, 29, 250, 17, 101, 215, 197, 34, 187, 138, 207, 134, 12, 221, 130, 14, 237, 225, 224, 226, 162, 211, 255, 46, 37, 162, 143, 178, 201, 146, 233, 94, 143, 62, 212, 246, 124, 34, 222, 40, 179, 136 },
                            PasswordSalt = new byte[] { 156, 76, 71, 67, 96, 150, 130, 48, 193, 2, 175, 27, 175, 72, 91, 255, 245, 251, 137, 55, 230, 143, 132, 181, 86, 214, 226, 129, 55, 79, 208, 242, 62, 181, 227, 47, 218, 14, 69, 192, 203, 3, 55, 247, 174, 96, 119, 107, 67, 79, 135, 119, 137, 222, 143, 113, 30, 88, 166, 228, 198, 163, 146, 101 },
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Businesses", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Matches", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.Vehicles", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Notifications", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Payments", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Searches", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Subscriptions", b =>
                {
                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "Businesses")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "SubscriptionPlans")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Businesses");

                    b.Navigation("SubscriptionPlans");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Vehicles", b =>
                {
                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "Businesses")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.VehicleColor", "VehicleColor")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Businesses");

                    b.Navigation("VehicleColor");

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("Given.DataContext.Entities.User", b =>
                {
                    b.HasOne("Given.DataContext.Entities.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
