// <auto-generated />
using System;
using CLIMFinders.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLIMFinders.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206214534_modify Vehicle color table")]
    partial class modifyVehiclecolortable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Businesses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Searches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Subscriptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("TierId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.VehicleColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Turquoise"
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acura"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bentley"
                        },
                        new
                        {
                            Id = 6,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Buick"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cadillac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chrysler"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Genesis"
                        },
                        new
                        {
                            Id = 17,
                            Name = "GMC"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Infiniti"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lotus"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Maserati"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 31,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Saab"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ColorId");

                    b.HasIndex("MakeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Given.DataContext.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleNanme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleNanme = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            RoleNanme = "Users"
                        },
                        new
                        {
                            Id = 3,
                            RoleNanme = "Tow"
                        },
                        new
                        {
                            Id = 4,
                            RoleNanme = "Impound"
                        });
                });

            modelBuilder.Entity("Given.DataContext.Entities.SubscriptionPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(7356),
                            Amount = 0m,
                            Duration = 0,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(7373),
                            Tier = "Free Tier"
                        },
                        new
                        {
                            Id = 2,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(7376),
                            Amount = 10m,
                            Duration = 1,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(7377),
                            Tier = "Paid Tier"
                        });
                });

            modelBuilder.Entity("Given.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedById = 0,
                            AddedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(8388),
                            ConfirmedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(8392),
                            Email = "admin@admin.com",
                            FullName = "SuperAdmin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            ModifiedById = 0,
                            ModifiedOn = new DateTime(2025, 2, 7, 3, 15, 34, 303, DateTimeKind.Local).AddTicks(8389),
                            Password = "MDAwMA==",
                            PasswordHash = new byte[] { 239, 170, 80, 166, 166, 113, 58, 196, 118, 35, 169, 32, 58, 45, 18, 116, 219, 205, 45, 199, 104, 63, 53, 93, 121, 122, 108, 240, 140, 233, 252, 185, 2, 221, 11, 107, 16, 125, 241, 13, 225, 225, 16, 103, 82, 77, 4, 24, 123, 192, 41, 153, 103, 125, 64, 129, 195, 54, 21, 186, 48, 83, 242, 10, 174, 96, 60, 13, 94, 199, 129, 248, 35, 238, 154, 117, 220, 117, 61, 17, 95, 75, 220, 122, 213, 49, 30, 43, 177, 200, 176, 204, 157, 103, 249, 43, 185, 138, 198, 120, 15, 191, 79, 13, 236, 166, 199, 253, 56, 75, 169, 12, 156, 98, 252, 36, 195, 142, 249, 220, 40, 52, 115, 170, 80, 21, 109, 120 },
                            PasswordSalt = new byte[] { 63, 140, 203, 142, 49, 90, 109, 127, 166, 96, 124, 49, 116, 92, 22, 228, 13, 238, 3, 93, 134, 108, 59, 230, 23, 72, 30, 228, 211, 249, 45, 153, 37, 85, 243, 116, 94, 47, 188, 227, 119, 30, 167, 101, 13, 207, 224, 19, 245, 252, 41, 61, 161, 11, 132, 112, 193, 115, 80, 237, 105, 153, 42, 236 },
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Businesses", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Matches", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.Vehicles", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Notifications", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Payments", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Searches", b =>
                {
                    b.HasOne("Given.DataContext.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Subscriptions", b =>
                {
                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "Businesses")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "SubscriptionPlans")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Businesses");

                    b.Navigation("SubscriptionPlans");
                });

            modelBuilder.Entity("CLIMFinders.Domain.Entities.Vehicles", b =>
                {
                    b.HasOne("CLIMFinders.Domain.Entities.Businesses", "Businesses")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.VehicleColor", "VehicleColor")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CLIMFinders.Domain.Entities.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Businesses");

                    b.Navigation("VehicleColor");

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("Given.DataContext.Entities.User", b =>
                {
                    b.HasOne("Given.DataContext.Entities.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
